# Generated by Django 6.0.6 on 2026-06-15 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentorganiser',
            name='website',
        ),
        migrations.AddField(
            model_name='tournamentorganiser',
            name='location',
            field=models.CharField(default='Location not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload your certificate (PDF format)', null=True, upload_to='trainer_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='location',
            field=models.CharField(default='Location not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='myfirstapp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='myfirstapp.trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
