# Generated by Django 6.0.6 on 2026-07-01 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerfeedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='playerfeedback',
            name='team',
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='detailed_feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Constructive', 'Constructive'), ('Excellent', 'Excellent'), ('Needs Improvement', 'Needs Improvement')], default='Positive', max_length=30),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='improvements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='skill_category',
            field=models.CharField(choices=[('Physical Performance', 'Physical Performance'), ('Technical Skills', 'Technical Skills'), ('Tactical Awareness', 'Tactical Awareness'), ('Mental Performance', 'Mental Performance')], default='Physical Performance', max_length=50),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playerfeedback',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
