# Generated by Django 6.0.6 on 2026-07-07 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('registration_enabled', 'Registration Enabled'), ('registration_approval', 'Require Admin Approval'), ('allow_team_creation', 'Allow Team Creation'), ('allow_tournament_creation', 'Allow Tournament Creation'), ('maintenance_mode', 'Maintenance Mode'), ('max_team_size', 'Maximum Team Size'), ('default_user_role', 'Default User Role')], max_length=50, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Setting',
                'verbose_name_plural': 'Admin Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('is_moderated', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('register', 'User registered'), ('login', 'User logged in'), ('logout', 'User logged out'), ('profile_update', 'Profile updated'), ('team_create', 'Team created'), ('team_join', 'Team joined'), ('tournament_create', 'Tournament created'), ('tournament_join', 'Tournament joined'), ('password_reset', 'Password reset'), ('content_report', 'Content reported')], max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='admin_panel_user_id_f4ad68_idx'), models.Index(fields=['activity_type', '-created_at'], name='admin_panel_activit_4e37a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deactivate_user', 'Deactivate user'), ('reactivate_user', 'Reactivate user'), ('assign_role', 'Assign role'), ('remove_role', 'Remove role'), ('moderate_profile', 'Moderate profile'), ('create_role', 'Create role'), ('delete_role', 'Delete role'), ('user_login', 'User login'), ('user_logout', 'User logout')], max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='admin_panel_action_7f96b3_idx'), models.Index(fields=['actor', '-created_at'], name='admin_panel_actor_i_ba3f75_idx'), models.Index(fields=['target_user', '-created_at'], name='admin_panel_target__8e2cfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user', 'User'), ('team', 'Team'), ('tournament', 'Tournament'), ('profile', 'Profile'), ('comment', 'Comment'), ('other', 'Other')], max_length=20)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='admin_panel_status_26cd17_idx'), models.Index(fields=['reported_user', '-created_at'], name='admin_panel_reporte_d7de81_idx')],
            },
        ),
    ]
